apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: abda-it-env
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: abda123
  POSTGRES_DB: abda_services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: abda-it-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: abda-it-env
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-api
  namespace: abda-it-env
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping-api
  template:
    metadata:
      labels:
        app: shopping-api
    spec:
      containers:
        - name: shopping-api
          image: amara125/shopping-api:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-api-service
  namespace: abda-it-env
spec:
  selector:
    app: shopping-api
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer
