apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"shopping-web-service","namespace":"abda-it-env"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"shopping-web"},"type":"LoadBalancer"}}
  creationTimestamp: "2026-03-08T04:12:18Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  name: shopping-web-service
  namespace: abda-it-env
  resourceVersion: "3460454"
  uid: 9207b5ca-1cc9-4fe0-a91b-4e1b3467c68c
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 172.20.218.70
  clusterIPs:
  - 172.20.218.70
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31045
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: shopping-web
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: a9207b5ca1cc94fe0a91b4e1b3467c68-992991316.us-east-1.elb.amazonaws.com
